var Ieit=jQuery.Class.create({init:function(a){this.data=[];this.loadImagesListener(a)},getLength:function(){return this.data.length},getData:function(){return this.data},addClass:function(a){this.data[this.getLength()]=new IeitClass(a)},loadImagesListener:function(a){var b=this,d=$(a)[0];d.addEventListener("dragover",function(a){a.stopPropagation();a.preventDefault()},!1);d.addEventListener("drop",function(c){c.stopPropagation();c.preventDefault();for(var c=c.dataTransfer.files,d=$(a),f=0,g;g=c[f];f++)if(g.type.match("image.*")){var h=
new FileReader;h.onload=function(a){return function(c){d.append('<span><img class="thumb" src="'+c.target.result+'" title="'+a.name+'"/></span>');$(".thumb").draggable({axis:"x"});b.addClass(c.target.result)}}(g);h.readAsDataURL(g)}},!1);return!0},drawTrainingMatrixes:function(a){$(a).empty();for(var b=0;b<this.getLength();b++)this.data[b].drawTrainingMatrix(a)},training:function(a){a=jQuery.extend({selectionLevelSel:"#sel-level",admissionSel:"#admission",kfeType:"shannon"},a);this.trainingBasic=
new IeitTraining(this.data,{selectionLevel:$(a.selectionLevelSel).val(),admission:$(a.admissionSel).val(),kfeType:a.kfeType})}}),IeitClass=jQuery.Class.create({init:function(a){this.trainingMatrix=[];this.trainingMatrixCreate(a)},trainingMatrixCreate:function(a){var b=new Image,d=this;b.onload=function(){var a=document.createElement("canvas");a.width=b.width;a.height=b.height;var e=a.getContext("2d");e.drawImage(b,0,0);for(var e=e.getImageData(0,0,a.width,a.height),f=0;f<a.width;f++){d.trainingMatrix[f]=
[];for(var g=0;g<a.height;g++){var h=4*(g*e.width+f);d.trainingMatrix[f][g]=Math.floor(0.299*e.data[h]+0.587*e.data[h+1]+0.114*e.data[h+2])}}};b.src=a;return!0},drawTrainingMatrix:function(a){(new IeitDraw).imageFromMatrix(this.trainingMatrix,a)}}),IeitDraw=jQuery.Class.create({imageFromMatrix:function(a,b){b=$(b);$(b).append("<canvas></canvas>");var d=$("canvas:last-child",b)[0];d.width=a.length;d.height=a[0].length;for(var c=d.getContext("2d"),e=c.getImageData(0,0,d.width,d.height),f=0;f<e.width;f++)for(var g=
0;g<e.height;g++){var h=4*(f+g*d.width);e.data[h+0]=a[f][g];e.data[h+1]=a[f][g];e.data[h+2]=a[f][g];e.data[h+3]=255}c.putImageData(e,0,0)},slider:function(a){a=jQuery.extend({selector:"#slider",input:"#slider-input",value:0.53,min:0,max:1,step:0.01},a);$(a.selector).slider({value:a.value,min:a.min,max:a.max,step:a.step,slide:function(b,d){$(a.input).val(d.value)}});$(a.input).val($(a.selector).slider("value"))},gridFromArray:function(a){for(var a=jQuery.extend({arr:[],selector:"#grid",name:"\u041c\u0430\u0441\u0438\u0432 \u0435\u043b\u0435\u043c\u0435\u043d\u0442\u0456\u0432",
col_width:35,height:"auto",sub_arr:null},a),b=[],d=[],c=0;c<=a.arr.length;c++){d[c]=c;0==c&&(d[c]="\u2116");if(35>a.col_width&&c==a.arr.length)a.col_width=35;b[c]={name:"id"+c,index:"id"+c,width:a.col_width,height:15,sortable:!1}}jQuery(a.selector).jqGrid({datatype:"local",height:a.height,colNames:d,colModel:b,caption:a.name});b=[];for(c=0;c<a.arr.length;c++){b[c]={};b[c].id0=c+1;for(d=0;d<=(a.sub_arr?a.arr[c][a.sub_arr].length:a.arr[c].length);d++)eval("mydata["+c+"].id"+(d+1)+" = "+(a.sub_arr?a.arr[c][a.sub_arr][d]:
a.arr[c][d]))}for(c=0;c<=b.length;c++)jQuery(a.selector).jqGrid("addRowData",c+1,b[c])}});jQuery.fn.ieiPrintTables=function(a){for(var b=0;b<a.length;b++)$(this).append('<table id="tm'+b+'" />'),$("#tm"+b).jqGridFromArray({arr:DataBase.trainingMatrix[b],col_width:15,name:"\u041d\u0430\u0432\u0447\u0430\u043b\u044c\u043d\u0430 \u043c\u0430\u0442\u0440\u0438\u0446\u044f \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f \u2116"+(b+1),height:250})};
Highcharts.setOptions({lang:{resetZoom:"\u041f\u043e\u0432\u0435\u0440\u043d\u0443\u0442\u0438\u0441\u044f \u0434\u043e \u043f\u043e\u0432\u043d\u043e\u043c\u0430\u0441\u0448\u0442\u0430\u0431\u043d\u043e\u0433\u043e \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0443",loading:"\u0417\u0430\u0432\u0430\u043d\u0442\u0430\u0436\u0435\u043d\u043d\u044f..."}});var DataBase={};
$(function(){$("#tabs").tabs();$("#tabs").tabs("disable","tabs-exam");$("button").button();(new IeitDraw).slider({selector:"#admission-slider",input:"#admission",value:40,min:0,max:100,step:1});(new IeitDraw).slider({selector:"#sel-level-slider",input:"#sel-level"});$("#set-opt").buttonset();$("#set-opt").buttonset("disable");var a=new Ieit("#drop-zone");$(".matrix.training button").click(function(){a.drawTrainingMatrixes("#training-matrix")});$("#set-kfe").buttonset().change(function(){a.training({kfeType:$("input:checked",
this).attr("id")});a.trainingBasic.drawBinaryMatrixes("#binary-matrix");a.trainingBasic.drawEtalonVectors("#etalon-matrix");a.trainingBasic.printCharacteristics("#characteristics");a.trainingBasic.printOptimalRadius("#radius");a.trainingBasic.drawOptimization("#optimization-chart");a.trainingBasic.printCodeDistance("#code-distance")})});
var IeitTraining=jQuery.Class.create({init:function(a,b){this.options=jQuery.extend({selectionLevel:0.53,admission:40,kfeType:"shannon"},b);this.ieitData=a;this.data=[];for(var d=0;d<this.ieitData.length;d++)this.data[d]={};this.selectionLevel=b.selectionLevel;this.admission=b.admission;this.controlApprovals();this.binEtalon();this.codeDistance();this.neighbour();this.characteristics();this.optimalRadius()},controlApprovals:function(){for(var a=0;a<this.ieitData.length;a++){this.data[a].dk=[];this.data[a].ndk=
[];this.data[a].vdk=[];for(var b=0;b<this.ieitData[a].trainingMatrix.length;b++){for(var d=this.ieitData[a].trainingMatrix[b].length,c=this.data[a].dk[b]=0;c<d;c++)this.data[a].dk[b]+=this.ieitData[a].trainingMatrix[b][c];this.data[a].dk[b]/=d;this.data[a].dk[b]=Math.floor(this.data[a].dk[b]);this.data[a].ndk[b]=this.data[a].dk[b]-this.admission;this.data[a].vdk[b]=this.data[a].dk[b]+ +this.admission}}},binEtalon:function(){for(var a=0;a<this.ieitData.length;a++){this.data[a].binaryMatrix=[];this.data[a].etalonVector=
[];for(var b=0;b<this.ieitData[a].trainingMatrix.length;b++){this.data[a].binaryMatrix[b]=[];for(var d=this.ieitData[a].trainingMatrix[b].length,c=0,e=0;e<d;e++){var f=this.ieitData[a].trainingMatrix[b][e],f=this.data[a].ndk[b]<=f&&this.data[a].vdk[b]>=f?1:0;this.data[a].binaryMatrix[b][e]=f;c+=f}c/=d;this.data[a].etalonVector[b]=c>=this.selectionLevel?1:0}}},drawBinaryMatrixes:function(a){$(a).empty();for(var b=0;b<this.data.length;b++){for(var d=[],c=0;c<this.data[b].binaryMatrix.length;c++){d[c]=
[];for(var e=0;e<this.data[b].binaryMatrix[c].length;e++)d[c][e]=255*Math.abs(this.data[b].binaryMatrix[c][e]-1)}(new IeitDraw).imageFromMatrix(d,a)}},drawEtalonVectors:function(a){$(a).empty();for(var b=0;b<this.data.length;b++){binary=[];for(var d=0;d<this.data[b].etalonVector.length;d++){binary[d]=[];for(var c=0;30>c;c++)binary[d][c]=255*Math.abs(this.data[b].etalonVector[d]-1)}(new IeitDraw).imageFromMatrix(binary,a)}},codeDistance:function(){for(var a=0;a<this.ieitData.length;a++){this.data[a].codeDistance=
[];for(var b=this.data[a].etalonVector.length,d=0;d<this.ieitData.length;d++)for(var c=this.data[a].codeDistance[d]=0;c<b;c++)this.data[a].codeDistance[d]+=(this.data[a].etalonVector[c]+this.data[d].etalonVector[c])%2}},printCodeDistance:function(a){$(a).html("<table id='code-distance-table' />");(new IeitDraw).gridFromArray({selector:"#code-distance-table",arr:this.data,sub_arr:"codeDistance",name:"\u041a\u043e\u0434\u043e\u0432\u0430 \u0432\u0456\u0434\u0441\u0442\u0430\u043d\u044c",col_width:45})},
neighbour:function(){for(var a=0;a<this.data.length;a++){var b=this.data[a].binaryMatrix[0].length;this.data[a].neighbour=[];for(var d=this.data[a].neighbour.nb=0;d<this.data.length;d++)if(0==this.data[a].codeDistance[this.data[a].neighbour.nb]||0!=this.data[a].codeDistance[d]&&this.data[a].codeDistance[this.data[a].neighbour.nb]>this.data[a].codeDistance[d])this.data[a].neighbour.nb=d;for(d=0;d<b;d++){for(var c=0,e=0,f=0;f<this.data[a].etalonVector.length;f++)c+=(this.data[a].etalonVector[f]+ +this.data[a].binaryMatrix[d][f])%
2,e+=(this.data[a].etalonVector[f]+ +this.data[this.data[a].neighbour.nb].binaryMatrix[d][f])%2;this.data[a].neighbour[d]=[];this.data[a].neighbour[d].sk1=c;this.data[a].neighbour[d].sk2=e}}},printSK:function(){},shannonKfe:function(a,b,d,c){return 1+0.5*((a&&a+c?a/(a+c)*Math.log(a/(a+c))/Math.log(2):0)+(d&&d+b?d/(d+b)*Math.log(d/(d+b))/Math.log(2):0)+(b&&d+b?b/(d+b)*Math.log(b/(d+b))/Math.log(2):0)+(c&&a+c?c/(a+c)*Math.log(c/(a+c))/Math.log(2):0))},kulbakKfe:function(a,b,d,c){console.log("kulbak");
return 0!=d+c&&0!=a+b?0.5*(Math.log((d+c)/(a+b))/Math.log(2))*(d+c-a-b):0},characteristics:function(){for(var a=0;a<this.data.length;a++){var b=this.data[a].binaryMatrix[0].length,d=this.data[a].codeDistance[this.data[a].neighbour.nb];this.data[a].kfe=[];for(var c=0;c<d;c++){this.data[a].kfe[c]=[];for(var e=this.data[a].kfe[c].k1=this.data[a].kfe[c].k2=this.data[a].kfe[c].k3=this.data[a].kfe[c].k4=0;e<b;e++)this.data[a].neighbour[e].sk1<=c?this.data[a].kfe[c].k1++:this.data[a].kfe[c].k2++,this.data[a].neighbour[e].sk2<=
c?this.data[a].kfe[c].k3++:this.data[a].kfe[c].k4++;this.data[a].kfe[c].d1=this.data[a].kfe[c].k1/b;this.data[a].kfe[c].alpha=this.data[a].kfe[c].k2/b;this.data[a].kfe[c].beta=this.data[a].kfe[c].k3/b;this.data[a].kfe[c].d2=this.data[a].kfe[c].k4/b;e=this.shannonKfe;if("shannon"!=this.options.kfeType)e=this.kulbakKfe;this.data[a].kfe[c].kfe=e(this.data[a].kfe[c].alpha,this.data[a].kfe[c].beta,this.data[a].kfe[c].d1,this.data[a].kfe[c].d2)}}},printCharacteristics:function(a){$(a).empty();for(var b=
0;b<this.data.length;b++){var d=this.data[b].codeDistance[this.data[b].neighbour.nb];$(a).append('<table id="characteristics-table-'+b+'" />');var c=$("#characteristics-table-"+b);jQuery(c).jqGrid({datatype:"local",height:"auto",colNames:"D,K1,K2,K3,K4,D1,alpha,D2,beta,\u041a\u0424\u0415".split(","),colModel:[{name:"d",width:25,sorttype:"int"},{name:"k1",width:45},{name:"k2",width:45},{name:"k3",width:45},{name:"k4",width:45},{name:"d1",width:45},{name:"alpha",width:45},{name:"d2",width:45},{name:"beta",
width:45},{name:"kfe",width:170}],caption:"\u0422\u043e\u0447\u043d\u0456\u0441\u043d\u0456 \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438 \u043a\u043b\u0430\u0441\u0443 \u2116"+ +(b+1),rowNum:d,hiddengrid:!0});for(var e=0;e<d;e++)jQuery(c).jqGrid("addRowData",e,{d:e,k1:this.data[b].kfe[e].k1,k2:this.data[b].kfe[e].k2,k3:this.data[b].kfe[e].k3,k4:this.data[b].kfe[e].k4,d1:this.data[b].kfe[e].d1,alpha:this.data[b].kfe[e].alpha,d2:this.data[b].kfe[e].d2,beta:this.data[b].kfe[e].beta,
kfe:this.data[b].kfe[e].kfe})}},optimalRadius:function(){for(var a=0;a<this.data.length;a++){this.data[a].trainingData={};this.data[a].trainingData.d=0;this.data[a].trainingData.kfe=0;for(var b=this.data[a].codeDistance[this.data[a].neighbour.nb],d=0;d<b;d++)if(0.5<=this.data[a].kfe[d].d1&&0.5<=this.data[a].kfe[d].d2&&this.data[a].kfe[d].kfe>this.data[a].trainingData.kfe)this.data[a].trainingData.kfe=this.data[a].kfe[d].kfe,this.data[a].trainingData.d=d}},printOptimalRadius:function(a){$(a).html('<table id="radius-table" />');
a=$("#radius-table");jQuery(a).jqGrid({datatype:"local",height:"auto",colNames:["\u041a\u043b\u0430\u0441","\u041a\u0424\u0415","\u041e\u043f\u0442\u0438\u043c\u0430\u043b\u044c\u043d\u0438\u0439 \u0440\u0430\u0434\u0456\u0443\u0441"],colModel:[{name:"klas",width:50},{name:"kfe",width:200},{name:"d",width:200}],caption:"\u041e\u043f\u0442\u0438\u043c\u0430\u043b\u044c\u043d\u0456 \u0440\u0430\u0434\u0456\u0443\u0441\u0438"});for(var b=0;b<this.data.length;b++)jQuery(a).jqGrid("addRowData",b+1,{klas:b+
1,kfe:this.data[b].trainingData.kfe,d:this.data[b].trainingData.d})},drawOptimization:function(a){$(a).empty();$(a).accordion("destroy");for(var b=0;b<this.data.length;b++){$(a).append('<h3><a href="#class'+(b+1)+'">\u0413\u0440\u0430\u0444\u0456\u043a \u0434\u043b\u044f '+(b+1)+'-\u0433\u043e \u043a\u043b\u0430\u0441\u0443</a></h3><div id="optimization-container-'+b+'" style="width: 488px; height: 300px; margin: 0 auto"></div>');for(var d=this.data[b].codeDistance[this.data[b].neighbour.nb],c=[],
e=[],f=0;f<d;f++)0.5<=this.data[b].kfe[f].d1&&0.5<=this.data[b].kfe[f].d2?(e[f]=this.data[b].kfe[f].kfe,c[f]=0):(e[f]=0,c[f]=this.data[b].kfe[f].kfe);new Highcharts.Chart({chart:{renderTo:"optimization-container-"+b,defaultSeriesType:"column",zoomType:"xy"},title:{text:"\u0417\u0430\u043b\u0435\u0436\u043d\u0456\u0441\u0442\u044c \u041a\u0424\u0415 \u0432\u0456\u0434 \u0440\u0430\u0434\u0456\u0443\u0441\u0443"},subtitle:{text:"\u0434\u043b\u044f \u043a\u043b\u0430\u0441\u0443 \u2116"+ +(b+1)},xAxis:{min:-1,
title:{text:"\u0420\u0430\u0434\u0456\u0443\u0441"}},yAxis:{min:0,title:{text:"\u041a\u0424\u0415"}},tooltip:{formatter:function(){return"E("+this.x+") = "+this.y}},plotOptions:{column:{pointPadding:0.01,groupPadding:0.01,borderWidth:0},series:{stacking:"normal"}},series:[{name:"\u041d\u0435 \u0440\u043e\u0431\u043e\u0447\u0430 \u043e\u0431\u043b\u0430\u0441\u0442\u044c",data:c},{name:"\u0420\u043e\u0431\u043e\u0447\u0430 \u043e\u0431\u043b\u0430\u0441\u0442\u044c",data:e}]})}$(a).accordion({navigation:!0,
autoHeight:!1})}});